// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BeginRecenter() {
  return window['go']['main']['App']['BeginRecenter']();
}

export function ConfirmRecenter() {
  return window['go']['main']['App']['ConfirmRecenter']();
}

export function GetParams() {
  return window['go']['main']['App']['GetParams']();
}

export function PickPoint(arg1, arg2) {
  return window['go']['main']['App']['PickPoint'](arg1, arg2);
}

export function ResetMouse() {
  return window['go']['main']['App']['ResetMouse']();
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function ToggleTracking(arg1) {
  return window['go']['main']['App']['ToggleTracking'](arg1);
}

export function UpdateParams(arg1) {
  return window['go']['main']['App']['UpdateParams'](arg1);
}
