// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function BeginRecenter():Promise<void>;

export function ConfirmRecenter():Promise<void>;

export function GetParams():Promise<config.Params>;

export function PickPoint(arg1:number,arg2:number):Promise<void>;

export function ResetMouse():Promise<void>;

export function Start():Promise<void>;

export function Stop():Promise<void>;

export function ToggleTracking(arg1:boolean):Promise<void>;

export function UpdateParams(arg1:config.Params):Promise<void>;
