// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function GetParams():Promise<config.AllParams>;

export function Recenter():Promise<void>;

export function SaveParams(arg1:config.AllParams):Promise<void>;

export function SetPickPoint(arg1:number,arg2:number):Promise<void>;

export function Start():Promise<void>;

export function Stop():Promise<void>;

export function ToggleTracking(arg1:boolean):Promise<void>;

export function UpdateParams(arg1:config.AllParams):Promise<void>;
