// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetParams() {
  return window['go']['main']['App']['GetParams']();
}

export function Recenter() {
  return window['go']['main']['App']['Recenter']();
}

export function SaveParams(arg1) {
  return window['go']['main']['App']['SaveParams'](arg1);
}

export function SetPickPoint(arg1, arg2) {
  return window['go']['main']['App']['SetPickPoint'](arg1, arg2);
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function ToggleTracking(arg1) {
  return window['go']['main']['App']['ToggleTracking'](arg1);
}

export function UpdateParams(arg1) {
  return window['go']['main']['App']['UpdateParams'](arg1);
}
